//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Friend_Utilisateur", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Utilisateur), "Friend", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Friend), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Friend_UtilisateurLinked", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Utilisateur), "Friend", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Friend), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_MessageRight_MessageRight", "Wall", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Wall), "MessageRight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.MessageRight), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_MessageRight_Utilisateur", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Utilisateur), "MessageRight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.MessageRight), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_MP_Destinataire", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Supbook.Web.Utilisateur), "MP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.MP), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_MP_Utilisateur", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Supbook.Web.Utilisateur), "MP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.MP), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Utilisateur_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Supbook.Web.Role), "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Utilisateur), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Wall_Utilisateur", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Supbook.Web.Utilisateur), "Wall", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Wall), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_FriendGroup_Group", "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Group), "FriendGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.FriendGroup), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_FriendGroup_Utilisateur", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Utilisateur), "FriendGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.FriendGroup), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Like_Like", "Utilisateur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Utilisateur), "Like", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Like), true)]
[assembly: EdmRelationshipAttribute("SupbookModel", "FK_Like_Wall", "Wall", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Supbook.Web.Wall), "Like", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Supbook.Web.Like), true)]

#endregion

namespace Supbook.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SupbookEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SupbookEntities object using the connection string found in the 'SupbookEntities' section of the application configuration file.
        /// </summary>
        public SupbookEntities() : base("name=SupbookEntities", "SupbookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupbookEntities object.
        /// </summary>
        public SupbookEntities(string connectionString) : base(connectionString, "SupbookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupbookEntities object.
        /// </summary>
        public SupbookEntities(EntityConnection connection) : base(connection, "SupbookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Friend> Friends
        {
            get
            {
                if ((_Friends == null))
                {
                    _Friends = base.CreateObjectSet<Friend>("Friends");
                }
                return _Friends;
            }
        }
        private ObjectSet<Friend> _Friends;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Group> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Group>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Group> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MessageRight> MessageRights
        {
            get
            {
                if ((_MessageRights == null))
                {
                    _MessageRights = base.CreateObjectSet<MessageRight>("MessageRights");
                }
                return _MessageRights;
            }
        }
        private ObjectSet<MessageRight> _MessageRights;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MP> MPs
        {
            get
            {
                if ((_MPs == null))
                {
                    _MPs = base.CreateObjectSet<MP>("MPs");
                }
                return _MPs;
            }
        }
        private ObjectSet<MP> _MPs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Utilisateur> Utilisateurs
        {
            get
            {
                if ((_Utilisateurs == null))
                {
                    _Utilisateurs = base.CreateObjectSet<Utilisateur>("Utilisateurs");
                }
                return _Utilisateurs;
            }
        }
        private ObjectSet<Utilisateur> _Utilisateurs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Wall> Walls
        {
            get
            {
                if ((_Walls == null))
                {
                    _Walls = base.CreateObjectSet<Wall>("Walls");
                }
                return _Walls;
            }
        }
        private ObjectSet<Wall> _Walls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FriendGroup> FriendGroups
        {
            get
            {
                if ((_FriendGroups == null))
                {
                    _FriendGroups = base.CreateObjectSet<FriendGroup>("FriendGroups");
                }
                return _FriendGroups;
            }
        }
        private ObjectSet<FriendGroup> _FriendGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Like> Likes
        {
            get
            {
                if ((_Likes == null))
                {
                    _Likes = base.CreateObjectSet<Like>("Likes");
                }
                return _Likes;
            }
        }
        private ObjectSet<Like> _Likes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Friends EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFriends(Friend friend)
        {
            base.AddObject("Friends", friend);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Group group)
        {
            base.AddObject("Groups", group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessageRights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessageRights(MessageRight messageRight)
        {
            base.AddObject("MessageRights", messageRight);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMPs(MP mP)
        {
            base.AddObject("MPs", mP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Utilisateurs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUtilisateurs(Utilisateur utilisateur)
        {
            base.AddObject("Utilisateurs", utilisateur);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Walls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWalls(Wall wall)
        {
            base.AddObject("Walls", wall);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FriendGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFriendGroups(FriendGroup friendGroup)
        {
            base.AddObject("FriendGroups", friendGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Likes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLikes(Like like)
        {
            base.AddObject("Likes", like);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Friend")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Friend : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Friend object.
        /// </summary>
        /// <param name="idFriend">Initial value of the IdFriend property.</param>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        /// <param name="idUserLinked">Initial value of the IdUserLinked property.</param>
        public static Friend CreateFriend(global::System.Int32 idFriend, global::System.Int32 idUser, global::System.Int32 idUserLinked)
        {
            Friend friend = new Friend();
            friend.IdFriend = idFriend;
            friend.IdUser = idUser;
            friend.IdUserLinked = idUserLinked;
            return friend;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFriend
        {
            get
            {
                return _IdFriend;
            }
            set
            {
                if (_IdFriend != value)
                {
                    OnIdFriendChanging(value);
                    ReportPropertyChanging("IdFriend");
                    _IdFriend = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFriend");
                    OnIdFriendChanged();
                }
            }
        }
        private global::System.Int32 _IdFriend;
        partial void OnIdFriendChanging(global::System.Int32 value);
        partial void OnIdFriendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUserLinked
        {
            get
            {
                return _IdUserLinked;
            }
            set
            {
                OnIdUserLinkedChanging(value);
                ReportPropertyChanging("IdUserLinked");
                _IdUserLinked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUserLinked");
                OnIdUserLinkedChanged();
            }
        }
        private global::System.Int32 _IdUserLinked;
        partial void OnIdUserLinkedChanging(global::System.Int32 value);
        partial void OnIdUserLinkedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Friend_Utilisateur", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_Utilisateur", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_Utilisateur", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_Utilisateur", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_Friend_Utilisateur", "Utilisateur", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Friend_UtilisateurLinked", "Utilisateur")]
        public Utilisateur UtilisateurLinked
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_UtilisateurLinked", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_UtilisateurLinked", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurLinkedReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Friend_UtilisateurLinked", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_Friend_UtilisateurLinked", "Utilisateur", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="FriendGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FriendGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FriendGroup object.
        /// </summary>
        /// <param name="idFriendGroup">Initial value of the IdFriendGroup property.</param>
        /// <param name="idGroup">Initial value of the IdGroup property.</param>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        public static FriendGroup CreateFriendGroup(global::System.Int32 idFriendGroup, global::System.Int32 idGroup, global::System.Int32 idUser)
        {
            FriendGroup friendGroup = new FriendGroup();
            friendGroup.IdFriendGroup = idFriendGroup;
            friendGroup.IdGroup = idGroup;
            friendGroup.IdUser = idUser;
            return friendGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFriendGroup
        {
            get
            {
                return _IdFriendGroup;
            }
            set
            {
                if (_IdFriendGroup != value)
                {
                    OnIdFriendGroupChanging(value);
                    ReportPropertyChanging("IdFriendGroup");
                    _IdFriendGroup = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFriendGroup");
                    OnIdFriendGroupChanged();
                }
            }
        }
        private global::System.Int32 _IdFriendGroup;
        partial void OnIdFriendGroupChanging(global::System.Int32 value);
        partial void OnIdFriendGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGroup
        {
            get
            {
                return _IdGroup;
            }
            set
            {
                OnIdGroupChanging(value);
                ReportPropertyChanging("IdGroup");
                _IdGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdGroup");
                OnIdGroupChanged();
            }
        }
        private global::System.Int32 _IdGroup;
        partial void OnIdGroupChanging(global::System.Int32 value);
        partial void OnIdGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_FriendGroup_Group", "Group")]
        public Group Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("SupbookModel.FK_FriendGroup_Group", "Group").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("SupbookModel.FK_FriendGroup_Group", "Group").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Group> GroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("SupbookModel.FK_FriendGroup_Group", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Group>("SupbookModel.FK_FriendGroup_Group", "Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_FriendGroup_Utilisateur", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_FriendGroup_Utilisateur", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_FriendGroup_Utilisateur", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_FriendGroup_Utilisateur", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_FriendGroup_Utilisateur", "Utilisateur", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="idGroup">Initial value of the IdGroup property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="idOwner">Initial value of the IdOwner property.</param>
        public static Group CreateGroup(global::System.Int32 idGroup, global::System.String name, global::System.Int32 idOwner)
        {
            Group group = new Group();
            group.IdGroup = idGroup;
            group.Name = name;
            group.IdOwner = idOwner;
            return group;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGroup
        {
            get
            {
                return _IdGroup;
            }
            set
            {
                if (_IdGroup != value)
                {
                    OnIdGroupChanging(value);
                    ReportPropertyChanging("IdGroup");
                    _IdGroup = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdGroup");
                    OnIdGroupChanged();
                }
            }
        }
        private global::System.Int32 _IdGroup;
        partial void OnIdGroupChanging(global::System.Int32 value);
        partial void OnIdGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdOwner
        {
            get
            {
                return _IdOwner;
            }
            set
            {
                OnIdOwnerChanging(value);
                ReportPropertyChanging("IdOwner");
                _IdOwner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdOwner");
                OnIdOwnerChanged();
            }
        }
        private global::System.Int32 _IdOwner;
        partial void OnIdOwnerChanging(global::System.Int32 value);
        partial void OnIdOwnerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_FriendGroup_Group", "FriendGroup")]
        public EntityCollection<FriendGroup> FriendGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendGroup>("SupbookModel.FK_FriendGroup_Group", "FriendGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendGroup>("SupbookModel.FK_FriendGroup_Group", "FriendGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Like")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Like : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Like object.
        /// </summary>
        /// <param name="idLike">Initial value of the IdLike property.</param>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        /// <param name="idWall">Initial value of the IdWall property.</param>
        public static Like CreateLike(global::System.Int32 idLike, global::System.Int32 idUser, global::System.Int32 idWall)
        {
            Like like = new Like();
            like.IdLike = idLike;
            like.IdUser = idUser;
            like.IdWall = idWall;
            return like;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdLike
        {
            get
            {
                return _IdLike;
            }
            set
            {
                if (_IdLike != value)
                {
                    OnIdLikeChanging(value);
                    ReportPropertyChanging("IdLike");
                    _IdLike = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdLike");
                    OnIdLikeChanged();
                }
            }
        }
        private global::System.Int32 _IdLike;
        partial void OnIdLikeChanging(global::System.Int32 value);
        partial void OnIdLikeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWall
        {
            get
            {
                return _IdWall;
            }
            set
            {
                OnIdWallChanging(value);
                ReportPropertyChanging("IdWall");
                _IdWall = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdWall");
                OnIdWallChanged();
            }
        }
        private global::System.Int32 _IdWall;
        partial void OnIdWallChanging(global::System.Int32 value);
        partial void OnIdWallChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Like_Like", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Like_Like", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Like_Like", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Like_Like", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_Like_Like", "Utilisateur", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Like_Wall", "Wall")]
        public Wall Wall
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_Like_Wall", "Wall").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_Like_Wall", "Wall").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Wall> WallReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_Like_Wall", "Wall");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Wall>("SupbookModel.FK_Like_Wall", "Wall", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="MessageRight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageRight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MessageRight object.
        /// </summary>
        /// <param name="idMessageRight">Initial value of the IdMessageRight property.</param>
        /// <param name="idWall">Initial value of the IdWall property.</param>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        public static MessageRight CreateMessageRight(global::System.Int32 idMessageRight, global::System.Int32 idWall, global::System.Int32 idUser)
        {
            MessageRight messageRight = new MessageRight();
            messageRight.IdMessageRight = idMessageRight;
            messageRight.IdWall = idWall;
            messageRight.IdUser = idUser;
            return messageRight;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMessageRight
        {
            get
            {
                return _IdMessageRight;
            }
            set
            {
                if (_IdMessageRight != value)
                {
                    OnIdMessageRightChanging(value);
                    ReportPropertyChanging("IdMessageRight");
                    _IdMessageRight = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMessageRight");
                    OnIdMessageRightChanged();
                }
            }
        }
        private global::System.Int32 _IdMessageRight;
        partial void OnIdMessageRightChanging(global::System.Int32 value);
        partial void OnIdMessageRightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWall
        {
            get
            {
                return _IdWall;
            }
            set
            {
                OnIdWallChanging(value);
                ReportPropertyChanging("IdWall");
                _IdWall = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdWall");
                OnIdWallChanged();
            }
        }
        private global::System.Int32 _IdWall;
        partial void OnIdWallChanging(global::System.Int32 value);
        partial void OnIdWallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MessageRight_MessageRight", "Wall")]
        public Wall Wall
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_MessageRight_MessageRight", "Wall").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_MessageRight_MessageRight", "Wall").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Wall> WallReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wall>("SupbookModel.FK_MessageRight_MessageRight", "Wall");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Wall>("SupbookModel.FK_MessageRight_MessageRight", "Wall", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MessageRight_Utilisateur", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MessageRight_Utilisateur", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MessageRight_Utilisateur", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MessageRight_Utilisateur", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_MessageRight_Utilisateur", "Utilisateur", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="MP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MP object.
        /// </summary>
        /// <param name="idMp">Initial value of the IdMp property.</param>
        public static MP CreateMP(global::System.Int32 idMp)
        {
            MP mP = new MP();
            mP.IdMp = idMp;
            return mP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMp
        {
            get
            {
                return _IdMp;
            }
            set
            {
                if (_IdMp != value)
                {
                    OnIdMpChanging(value);
                    ReportPropertyChanging("IdMp");
                    _IdMp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMp");
                    OnIdMpChanged();
                }
            }
        }
        private global::System.Int32 _IdMp;
        partial void OnIdMpChanging(global::System.Int32 value);
        partial void OnIdMpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateMP
        {
            get
            {
                return _DateMP;
            }
            set
            {
                OnDateMPChanging(value);
                ReportPropertyChanging("DateMP");
                _DateMP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMP");
                OnDateMPChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateMP;
        partial void OnDateMPChanging(Nullable<global::System.DateTime> value);
        partial void OnDateMPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxtMP
        {
            get
            {
                return _TxtMP;
            }
            set
            {
                OnTxtMPChanging(value);
                ReportPropertyChanging("TxtMP");
                _TxtMP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxtMP");
                OnTxtMPChanged();
            }
        }
        private global::System.String _TxtMP;
        partial void OnTxtMPChanging(global::System.String value);
        partial void OnTxtMPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private Nullable<global::System.Int32> _IdUser;
        partial void OnIdUserChanging(Nullable<global::System.Int32> value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdContact
        {
            get
            {
                return _IdContact;
            }
            set
            {
                OnIdContactChanging(value);
                ReportPropertyChanging("IdContact");
                _IdContact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdContact");
                OnIdContactChanged();
            }
        }
        private Nullable<global::System.Int32> _IdContact;
        partial void OnIdContactChanging(Nullable<global::System.Int32> value);
        partial void OnIdContactChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MP_Destinataire", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Destinataire", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Destinataire", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Destinataire", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_MP_Destinataire", "Utilisateur", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MP_Utilisateur", "Utilisateur")]
        public Utilisateur UtilisateurDestinataire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Utilisateur", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Utilisateur", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurDestinataireReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_MP_Utilisateur", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_MP_Utilisateur", "Utilisateur", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="idRole">Initial value of the IdRole property.</param>
        public static Role CreateRole(global::System.Int32 idRole)
        {
            Role role = new Role();
            role.IdRole = idRole;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRole
        {
            get
            {
                return _IdRole;
            }
            set
            {
                if (_IdRole != value)
                {
                    OnIdRoleChanging(value);
                    ReportPropertyChanging("IdRole");
                    _IdRole = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRole");
                    OnIdRoleChanged();
                }
            }
        }
        private global::System.Int32 _IdRole;
        partial void OnIdRoleChanging(global::System.Int32 value);
        partial void OnIdRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lbRole
        {
            get
            {
                return _lbRole;
            }
            set
            {
                OnlbRoleChanging(value);
                ReportPropertyChanging("lbRole");
                _lbRole = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lbRole");
                OnlbRoleChanged();
            }
        }
        private global::System.String _lbRole;
        partial void OnlbRoleChanging(global::System.String value);
        partial void OnlbRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txtRole
        {
            get
            {
                return _txtRole;
            }
            set
            {
                OntxtRoleChanging(value);
                ReportPropertyChanging("txtRole");
                _txtRole = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txtRole");
                OntxtRoleChanged();
            }
        }
        private global::System.String _txtRole;
        partial void OntxtRoleChanging(global::System.String value);
        partial void OntxtRoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Utilisateur_Role", "Utilisateur")]
        public EntityCollection<Utilisateur> Utilisateurs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Utilisateur>("SupbookModel.FK_Utilisateur_Role", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Utilisateur>("SupbookModel.FK_Utilisateur_Role", "Utilisateur", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Utilisateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Utilisateur : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Utilisateur object.
        /// </summary>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="prenom">Initial value of the Prenom property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="mail">Initial value of the Mail property.</param>
        /// <param name="preventPublicPublish">Initial value of the PreventPublicPublish property.</param>
        public static Utilisateur CreateUtilisateur(global::System.Int32 idUser, global::System.String nom, global::System.String prenom, global::System.String login, global::System.String password, global::System.String mail, global::System.Boolean preventPublicPublish)
        {
            Utilisateur utilisateur = new Utilisateur();
            utilisateur.IdUser = idUser;
            utilisateur.Nom = nom;
            utilisateur.Prenom = prenom;
            utilisateur.Login = login;
            utilisateur.Password = password;
            utilisateur.Mail = mail;
            utilisateur.PreventPublicPublish = preventPublicPublish;
            return utilisateur;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                if (_IdUser != value)
                {
                    OnIdUserChanging(value);
                    ReportPropertyChanging("IdUser");
                    _IdUser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUser");
                    OnIdUserChanged();
                }
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDeNaissance
        {
            get
            {
                return _DateDeNaissance;
            }
            set
            {
                OnDateDeNaissanceChanging(value);
                ReportPropertyChanging("DateDeNaissance");
                _DateDeNaissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDeNaissance");
                OnDateDeNaissanceChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDeNaissance;
        partial void OnDateDeNaissanceChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDeNaissanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdRole
        {
            get
            {
                return _IdRole;
            }
            set
            {
                OnIdRoleChanging(value);
                ReportPropertyChanging("IdRole");
                _IdRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdRole");
                OnIdRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _IdRole;
        partial void OnIdRoleChanging(Nullable<global::System.Int32> value);
        partial void OnIdRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PreventPublicPublish
        {
            get
            {
                return _PreventPublicPublish;
            }
            set
            {
                OnPreventPublicPublishChanging(value);
                ReportPropertyChanging("PreventPublicPublish");
                _PreventPublicPublish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreventPublicPublish");
                OnPreventPublicPublishChanged();
            }
        }
        private global::System.Boolean _PreventPublicPublish;
        partial void OnPreventPublicPublishChanging(global::System.Boolean value);
        partial void OnPreventPublicPublishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Friend_Utilisateur", "Friend")]
        public EntityCollection<Friend> Friends
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Friend>("SupbookModel.FK_Friend_Utilisateur", "Friend");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Friend>("SupbookModel.FK_Friend_Utilisateur", "Friend", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MessageRight_Utilisateur", "MessageRight")]
        public EntityCollection<MessageRight> MessageRights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MessageRight>("SupbookModel.FK_MessageRight_Utilisateur", "MessageRight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MessageRight>("SupbookModel.FK_MessageRight_Utilisateur", "MessageRight", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MP_Destinataire", "MP")]
        public EntityCollection<MP> MyMPs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MP>("SupbookModel.FK_MP_Destinataire", "MP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MP>("SupbookModel.FK_MP_Destinataire", "MP", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MP_Utilisateur", "MP")]
        public EntityCollection<MP> ReceivedMPs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MP>("SupbookModel.FK_MP_Utilisateur", "MP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MP>("SupbookModel.FK_MP_Utilisateur", "MP", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Utilisateur_Role", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("SupbookModel.FK_Utilisateur_Role", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("SupbookModel.FK_Utilisateur_Role", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("SupbookModel.FK_Utilisateur_Role", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("SupbookModel.FK_Utilisateur_Role", "Role", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Wall_Utilisateur", "Wall")]
        public EntityCollection<Wall> Walls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wall>("SupbookModel.FK_Wall_Utilisateur", "Wall");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wall>("SupbookModel.FK_Wall_Utilisateur", "Wall", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_FriendGroup_Utilisateur", "FriendGroup")]
        public EntityCollection<FriendGroup> FriendGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendGroup>("SupbookModel.FK_FriendGroup_Utilisateur", "FriendGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendGroup>("SupbookModel.FK_FriendGroup_Utilisateur", "FriendGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Like_Like", "Like")]
        public EntityCollection<Like> Likes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Like>("SupbookModel.FK_Like_Like", "Like");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Like>("SupbookModel.FK_Like_Like", "Like", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SupbookModel", Name="Wall")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wall : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Wall object.
        /// </summary>
        /// <param name="idWall">Initial value of the IdWall property.</param>
        /// <param name="dateWall">Initial value of the DateWall property.</param>
        public static Wall CreateWall(global::System.Int32 idWall, global::System.DateTime dateWall)
        {
            Wall wall = new Wall();
            wall.IdWall = idWall;
            wall.DateWall = dateWall;
            return wall;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWall
        {
            get
            {
                return _IdWall;
            }
            set
            {
                if (_IdWall != value)
                {
                    OnIdWallChanging(value);
                    ReportPropertyChanging("IdWall");
                    _IdWall = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdWall");
                    OnIdWallChanged();
                }
            }
        }
        private global::System.Int32 _IdWall;
        partial void OnIdWallChanging(global::System.Int32 value);
        partial void OnIdWallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TitreWall
        {
            get
            {
                return _TitreWall;
            }
            set
            {
                OnTitreWallChanging(value);
                ReportPropertyChanging("TitreWall");
                _TitreWall = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TitreWall");
                OnTitreWallChanged();
            }
        }
        private global::System.String _TitreWall;
        partial void OnTitreWallChanging(global::System.String value);
        partial void OnTitreWallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxtWall
        {
            get
            {
                return _TxtWall;
            }
            set
            {
                OnTxtWallChanging(value);
                ReportPropertyChanging("TxtWall");
                _TxtWall = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxtWall");
                OnTxtWallChanged();
            }
        }
        private global::System.String _TxtWall;
        partial void OnTxtWallChanging(global::System.String value);
        partial void OnTxtWallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateWall
        {
            get
            {
                return _DateWall;
            }
            set
            {
                OnDateWallChanging(value);
                ReportPropertyChanging("DateWall");
                _DateWall = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateWall");
                OnDateWallChanged();
            }
        }
        private global::System.DateTime _DateWall;
        partial void OnDateWallChanging(global::System.DateTime value);
        partial void OnDateWallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private Nullable<global::System.Int32> _IdUser;
        partial void OnIdUserChanging(Nullable<global::System.Int32> value);
        partial void OnIdUserChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_MessageRight_MessageRight", "MessageRight")]
        public EntityCollection<MessageRight> MessageRights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MessageRight>("SupbookModel.FK_MessageRight_MessageRight", "MessageRight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MessageRight>("SupbookModel.FK_MessageRight_MessageRight", "MessageRight", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Wall_Utilisateur", "Utilisateur")]
        public Utilisateur Utilisateur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Wall_Utilisateur", "Utilisateur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Wall_Utilisateur", "Utilisateur").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilisateur> UtilisateurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilisateur>("SupbookModel.FK_Wall_Utilisateur", "Utilisateur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilisateur>("SupbookModel.FK_Wall_Utilisateur", "Utilisateur", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SupbookModel", "FK_Like_Wall", "Like")]
        public EntityCollection<Like> Likes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Like>("SupbookModel.FK_Like_Wall", "Like");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Like>("SupbookModel.FK_Like_Wall", "Like", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
